version: '3'

services:
  tm-timer:
    build: .
    container_name: toastmaster-timer
    restart: always
    ports:
      - "8081:80"
    networks:
      - tm-network

networks:
  tm-network:
    driver: bridge
